### PR TITLE
Check for bearer

### PR DESCRIPTION
**Pull request by RandomEtc**
As discussed in #6, add a stricter check for `Bearer` in the `Authorization` header.

Also fixed an issue in the `remove_grant` handler in the `simple.js` example.

### CODE REVIEW

**Comment by ammmir** [comment]
i already implemented your suggestion on the v1 branch in 8cb4ed0435ea277f1528860ec6ae88368f42608d

**Comment by RandomEtc** [comment]
Cool. Thanks. What's holding you back from merging and pushing a new release? Anything I can help with?

**Comment by ammmir** [comment]
I've pushed 1.0.0 to npm with no changes.

**Comment by RandomEtc** [comment]
Awesome - thanks!

**Pull request closed without merging**
