### PR TITLE
update for connect 2.0 (and backwards compat with 1.0)

### PR DESCRIPTION
**Pull request by coolaj86**

### CODE REVIEW

**Comment by timoxley** [comment]
+1 @ammmir  any update on this?

**Comment by coolaj86** [comment]
I do 

```
connect.router = require('connect_router');
```

Before I require oauth2-provider, as a workaround.

**Comment by timoxley** [comment]
nice fix. thanks aj.

**Comment by benatkin** [comment]
you should just publish your own package

**Comment by benatkin** [comment]
Thanks for merging this, and making my suggestion moot!

**Comment by ammmir** [comment]
@benatkin no worries, anything to avoid mutiny by forking!

**Pull request closed without merging**
